#!/bin/bash
#SBATCH -o /home/mpauls/Research_CAT/calculations/H2O_444/job.o%j   # Name of stdout output file(%j expands to jobId)
#SBATCH -e /home/mpauls/Research_CAT/calculations/H2O_444/job.e%j   # Name of stderr output file(%j expands to jobId)
#SBATCH -N 1                # Total number of nodes requested (16 cores/node)
#SBATCH -p large
#SBATCH --mem=122g
#SBATCH -J H2O_444

cd /home/mpauls/Research_CAT/calculations/H2O_444
hostname -s

export NCPU=`cat /proc/cpuinfo | grep processor| grep -v model | wc -l`
export I_MPI_PIN=true
export OMP_NUM_THREADS=1
ulimit -s unlimited

mpirun -np $NCPU /cluster/bin/ilinux_x86_64/vasp5/vasp_std > out

