Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1       O           9.36            7.88 
      2       H          -6.35           -5.35 
      3       H          -6.29           -5.30 

Madelung Energy (eV)     -6.16           -4.37 
