#!/usr/local_rwth/bin/zsh

###  1 processes, all on one node
#SBATCH --job-name=Test
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --constraint=Rocky8
### Limit for maximum memory per slot (in MB)
#SBATCH --mem-per-cpu=3900

### The time limit for the job in minutes (reaching this time limit, the process is signaled and killed)
#SBATCH --time=0-24:00:00

# declare the merged STDOUT/STDERR file
#SBATCH --output=output.%J.txt

#SBATCH --partition=c18m
#SBATCH --account=p0020506

### end of Slurm SBATCH definitions

### beginning of executable commands

### load the necessary module files

module load GCC/11.3.0 OpenMPI/4.1.4  ORCA/5.0.4

### your program goes here (a.out is an example)
/cvmfs/software.hpc.rwth.de/Linux/RH8/x86_64/intel/skylake_avx512/software/ORCA/5.0.4-gompi-2022a/bin/orca  orca.inp 

